# Generated by Django 3.0.6 on 2020-05-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200530_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='healthregister',
            name='health_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthregister',
            name='ill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthregister',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='Fotos_inmueble/'),
        ),
        migrations.AddField(
            model_name='healthregister',
            name='observations',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='healthregister',
            name='who_ill',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='health_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='who_health',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='who_risk',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transport_fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.transport'),
        ),
    ]
