# Generated by Django 3.0.6 on 2020-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200530_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
