# Generated by Django 3.0.6 on 2020-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_entity_entitytype_fk_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=1000)),
                ('op2', models.CharField(max_length=1000)),
                ('op3', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=5)),
            ],
        ),
    ]
