# Generated by Django 3.0.6 on 2020-05-31 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('answer_fk_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
                ('answer_fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
