# Generated by Django 3.0.6 on 2020-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthregister',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
