# Generated by Django 3.0.6 on 2020-05-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_healthregister_bad'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('schedule_fk_healthRegister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.healthRegister')),
            ],
        ),
    ]
