# Generated by Django 3.0.6 on 2020-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200530_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthregister',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
