# Generated by Django 3.0.6 on 2020-05-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_healthregister_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
