# Generated by Django 3.0.6 on 2020-05-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identification',
            new_name='id',
        ),
    ]
