# Generated by Django 3.0.6 on 2020-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200530_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
