# Generated by Django 3.0.6 on 2020-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_healthregister_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthregister',
            name='bad',
            field=models.BooleanField(default=False),
        ),
    ]
